# Analysis configuration for Flutter project
# Uses very_good_analysis for comprehensive, production-ready linting rules

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart" 
    - "**/*.mocks.dart"
    - "build/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Override specific rules from very_good_analysis if needed
    lines_longer_than_80_chars: false
    # Disabled deprecated rules mentioned in BUGS.md:
    # - always_require_non_null_named_parameters (removed in Dart 3.3.0)
    # - iterable_contains_unrelated_type (removed in Dart 3.3.0)
    # - list_remove_unrelated_type (removed in Dart 3.3.0)
    # - package_api_docs (removed in Dart 3.7.0)
    # - prefer_equal_for_default_values (removed in Dart 3.0.0)
    # - unsafe_html (removed in Dart 3.7.0)
