name: food_scanner
description: Food scanning app

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  http: ^1.1.0
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4
  mobile_scanner: ^5.2.3
  logger: ^2.0.2
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true